apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nequidev-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/anfedimo/kubernetes-nequi'
    targetRevision: main
    path: charts/nequidev-api
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true