cat <<EOF > argocd/sabana-argo-jenkins-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.jenkins.io'
    targetRevision: '*'
    chart: jenkins
    helm:
      values: |
        controller:
          serviceType: ClusterIP
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
EOF