apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-infra
  namespace: argocd
spec:
  project: default
  source:
    # AHORA SÍ: Apuntamos a tu repositorio personal
    repoURL: 'https://github.com/anfedimo/kubernetes-u-sabana'
    targetRevision: main
    path: charts/jenkins # Ruta donde guardaremos la configuración local
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true